name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Unit tests
      run: make test

    - name: Run gRPC Server (in background)
      run: |
        make run-server &  # Run server in background
        SERVER_PID=$!               # Capture PID to kill later
        sleep 3                     # Wait for server to start
        echo "SERVER_PID=$SERVER_PID" >> $GITHUB_ENV  # Store PID for cleanup

    - name: Run gRPC Client
      run: make run-client

    - name: Stop gRPC Server
      if: always()
      run: |
        kill $SERVER_PID
